# This Dockerfile is based on the latest ubuntu version
FROM ubuntu:latest

# Command to execute the image and the configuration
RUN apt-get update && apt-get upgrade -y

# Define the execution of the container
CMD ["echo", "Hello, World!"]
